#!/usr/bin/env python3
"""Regenerate goal-closure-audit-capture.md from verification-summary.txt."""
from __future__ import annotations

import os
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path


def main() -> int:
    repo_root = Path(subprocess.check_output(["git", "rev-parse", "--show-toplevel"], text=True).strip())
    tree = subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=repo_root, text=True).strip()
    out_dir = Path(
        os.environ.get(
            "SCRATCH",
            "/var/folders/z9/yr58561n1rj8_lqtzwkjt24m0000gp/T/grok-goal-cd5f675df757/implementer",
        )
    )
    summary_path = out_dir / "verification-summary.txt"
    dest = repo_root / "kb/raw/captures/goal-closure-audit-capture.md"

    if not summary_path.is_file():
        print(f"goal-capture-template: missing {summary_path}", file=sys.stderr)
        return 1

    summary = summary_path.read_text()
    tree_in_summary = next(
        (line.split(":", 1)[1].strip() for line in summary.splitlines() if line.startswith("verification_tree:")),
        "",
    )
    if tree_in_summary != tree:
        print(f"goal-capture-template: summary tree {tree_in_summary} != HEAD {tree}", file=sys.stderr)
        return 1

    updated = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    body = f"""---
title: Goal Closure Audit Capture
tags:
  - kb
  - raw
  - meta
aliases:
  - KB research ingest closure audit
kind: source-summary
status: active
updated: {updated}
source_count: 1
journal_ref: kb-research-ingest-goal-closure
---

# Goal Closure Audit Capture

Generated at verification tree `{tree}`. Numeric SSOT: scratch `verification-summary.txt` (verbatim below).

## Closure commands

```bash
bash kb/activity/goal-verify.sh
bash kb/activity/goal-hygiene-check.sh
bash kb/activity/goal-capture-template.sh
```

Verification contract: `kb/activity/goal-verification-contract.md`.

## verification-summary.txt (verbatim)

```text
{summary.rstrip()}
```

## Provenance

Regenerated by `goal-capture-template.sh`; do not hand-edit counts in this file.
"""
    tmp = dest.with_suffix(dest.suffix + f".work.{os.getpid()}")
    try:
        tmp.write_text(body)
        tmp.replace(dest)
    finally:
        if tmp.exists():
            tmp.unlink(missing_ok=True)
    print(f"goal-capture-template: wrote {dest} (tree={tree})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())