"""Shared chrome fragments for generated docs pages."""

from __future__ import annotations

from pathlib import Path

from wagents.catalog import CatalogNode
from wagents.site_model import LOCAL_INSTALLED_SOURCE_LABEL


def _is_local_path_like(value: str) -> bool:
    path = str(value or "").strip()
    if path.startswith(("http://", "https://", "github:")):
        return False
    if path.startswith(("~/", "$HOME/", "/Users/", "/home/", "/private/", "/tmp/")):
        return True
    return Path(path).is_absolute()


def display_source_path(node: CatalogNode) -> str:
    path = str(node.source_path)
    if node.source != "custom" and _is_local_path_like(path):
        return LOCAL_INSTALLED_SOURCE_LABEL
    home = str(Path.home())
    if path.startswith(home):
        return "~" + path[len(home) :]
    return path


def provenance_one_liner(node: CatalogNode) -> str:
    """Compact provenance for summary-mode page footers."""
    src = display_source_path(node)
    if node.kind == "skill":
        if node.source == "custom":
            return f"Generated from `{src}` via `wagents docs generate`."
        if node.source == "curated-external":
            return (
                f"Generated from authoring `docs/src/authoring/skills/{node.id}.mdx` "
                "and `skills-catalog-index.json`."
            )
        return f"Generated from `{src}`."
    if node.kind == "agent":
        return f"Generated from `{src}` via `wagents docs generate`."
    if node.kind == "mcp":
        return f"Generated from `mcp/{node.id}/` (`{src}`)."
    return "Generated by `wagents docs generate`."


def render_metadata_details(title: str, table_md: str) -> list[str]:
    """Render tab content as a collapsed details block for summary density."""
    return [
        '<details class="source-disclosure metadata-disclosure">',
        f"<summary>{title}</summary>",
        "",
        table_md,
        "",
        "</details>",
        "",
    ]
