allowBuilds:
  esbuild: true
  sharp: true

patchedDependencies:
  starlight-site-graph@0.5.0: patches/starlight-site-graph@0.5.0.patch

peerDependencyRules:
  allowedVersions:
    astro-integration-kit>astro: "^4.12.0 || ^5.0.0 || ^6.0.0"
