allowBuilds:
  esbuild: true
  sharp: true

patchedDependencies:
  starlight-site-graph@0.5.0: patches/starlight-site-graph@0.5.0.patch

peerDependencyRules:
  allowedVersions:
    starlight-plugin-icons>typescript: "^5 || ^6"
    vite-plugin-virtual>vite: "^2.0.0 || ^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0 || ^7.0.0 || ^8.0.0"
